In [27]:
import pandas as pd

path = "orders.csv"
df = pd.read_csv(path)

In [ ]:
#print the first 5 of the dataframe
df.head()
#print the general information on the dataframe
df.info()
#print the statistical summary of the data
df.describe()

In [29]:
#print the country in the dataframe
df.columns

Index(['order_id', 'customer_id', 'order_date', 'product_name', 'category',
       'quantity', 'price_per_unit', 'total_amount', 'shipping_status'],
      dtype='object')

In [ ]:
df[["product_name","category"]]

In [ ]:
#iloc selects data by its numerical position (index)
#provides the data on the 11th row and returns as a series
df.iloc[10]

In [ ]:
#print the list of rows with a shipping status that starts with A and excluded NaN
df[df["shipping_status"].str.startswith("A").notna()]

In [ ]:
#print the list of rows with a product name that starts with D
df[df["product_name"].str.startswith("D")]

In [ ]:
#sample of locating a specific row based on the given conditions
df.loc[(df["order_id"] == 1010) & (df["product_name"] == "Headphones")]

,order_id,customer_id,order_date,product_name,category,quantity,price_per_unit,total_amount,shipping_status
10,1010,5010,2026-01-02 01:00:00,Headphones,Electronics,5,150.0,600.0,Delivered

In [ ]:
#print the list of rows where shipping_status is null / NaN
df[df["shipping_status"].isna()]

In [ ]:
#filling in no values as Pending in the shipping_status column
df.fillna({"shipping_status": "Pending"}, inplace=True)

In [78]:
df[df["shipping_status"] == "Pending"]

,order_id,customer_id,order_date,product_name,category,quantity,price_per_unit,total_amount,shipping_status
15,1015,5002,2026-01-02 20:00:00,Laptop,Electronics,2,1200.0,2400.0,Pending
89,1089,5023,2026-02-15 20:00:00,Bookshelf,Furniture,3,120.0,360.0,Pending
129,1129,5039,2026-04-13 03:00:00,Bookshelf,Furniture,1,120.0,120.0,Pending
132,1132,5034,2026-04-04 14:00:00,Running Shoes,Apparel,2,110.0,220.0,Pending
142,1142,5013,2026-03-31 20:00:00,Smartphone,Electronics,1,800.0,800.0,Pending
148,1148,5025,2026-04-06 21:00:00,Hoodie,Apparel,2,45.0,90.0,Pending
173,1173,5005,2026-04-30 04:00:00,Desk Chair,Furniture,2,200.0,400.0,Pending
180,1180,5010,2026-02-19 02:00:00,Blender,Appliances,3,60.0,180.0,Pending
185,1185,5000,2026-03-06 00:00:00,Blender,Appliances,3,60.0,180.0,Pending
195,1195,5036,2026-03-31 01:00:00,Headphones,Electronics,4,150.0,600.0,Pending